let jogadores = [ {
    nome : "Gabigol",
    foto: "",
    atacante: true,
    brasileiro: true,
    ano2019: true,
    copa_america:true,
    santos: true,
    cruzeiro: false,
    copa_do_mundo: false,
    zagueiro: false,
    olimpiadas: true,
    libertadores: false,
    gremio: false,
    champions: false,
    pontos: 0,
    perguntas: ["Já jogou no santos", "Já ganhou a olímpiadas?"],
     },
     {
        nome : "Bruno Henrique",
        foto: "",
        atacante: true,
        brasileiro: true,
        ano2019: true,
        copa_america:false,
        santos: true,
        cruzeiro: false,
        copa_do_mundo: false,
        zagueiro: false,
        olimpiadas: false,
        libertadores: false,
        gremio: false,
        champions: false,
        pontos: 0,
        perguntas: ["Já jogou no santos"],
        }, 
        {
            nome : "Everton Ribeiro",
            foto: "",
            atacante: false,
            brasileiro: true,
            ano2019: true,
            copa_america:true,
            santos: false,
            cruzeiro: true,
            copa_do_mundo: false,
            zagueiro: false,
            olimpiadas: false,
            libertadores: false,
            gremio: false,
            champions: false,
            pontos: 0,
            perguntas: ["Já jogou no cruzeiro?"],
    },
    {
        nome : "Arrascaeta",
        foto: "",
        atacante: false,
        brasileiro: false,
        ano2019: true,
        copa_america: true,
        santos: false,
        cruzeiro: true,
        copa_do_mundo: false,
        zagueiro: false,
        olimpiadas: false,
        libertadores: false,
        gremio: false,
        champions: false,
        pontos:0,
        perguntas: ["Já jogou no cruzeiro?"],
}
]


let perguntas_iniciais = [
    "É atacante",
    "É brasileiro",
    "Está no flamengo desde 2019",
    "Jogou a última copa anérica"
]